.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. andiacoin_qt test_andiacoin_qt
clean: FORCE
	$(MAKE) -C .. andiacoin_qt_clean test_andiacoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_andiacoin_qt_check
andiacoin-qt andiacoin-qt.exe: FORCE
	 $(MAKE) -C .. andiacoin_qt
apk: FORCE
	$(MAKE) -C .. andiacoin_qt_apk
